music/urls.py
from django.conf.urls import url
from django.contrib import admin
from music import views
admin.autodiscover()

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<album_id>[0-9]+)/', views.detail, name="detail"),
    url(r'^songs/',views.songs, name="songs"),
]

songify/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from music import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=255)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + " - " + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index(request):
    details = Album.objects.all()
    c = {"details":details}
    return render(request, 'home.html', c)

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'detail.html', {'album':album})

def songs(request):
    try:
        song = Song.objects.all()
    except Song.DoesNotExist:
        raise Http404("Can't find songs")
    return render(request, 'songs.html', {'song':song})

music/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>{% block title %}Songify{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/basemain.css">
</head>
<body>
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">Songify</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'index' %}"><span class="glyphicon glyphicon-cd"></span>&nbsp;Albums</a></li>
        <li><a href="{% url 'songs' %}"><span class="glyphicon glyphicon-music"></span>&nbsp;Songs</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-plus"></span>&nbsp;Add Album</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-off"></span>&nbsp;Logout</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}
{% endblock %}

<div class="foot">
  <div id="playstatus"></div>
  <div id="currentSong" class="col-md-4 col-sm-4">
    <img style="float: left;" src="">
    <span>
    <h4>Song title</h4>
    <h5>Song-album || song-artist</h5>
  </span>
  </div>
  <div class="foot-in col-md-4 col-xs-12 col-sm-4">
    <span class="glyphicon glyphicon-step-backward"></span>&emsp;&emsp;
    <span class="glyphicon glyphicon-play"></span>&emsp;&emsp;
    <span class="glyphicon glyphicon-step-forward"></span>
  </div>
</div>

<script type="text/javascript" src="/static/js/jquery.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</body>
</html>

music/templates/detail.html
{% extends 'base.html' %}
<head>
    <title>{% block title %}{{ album.artist }}-{{ album.album_title }}{% endblock %}</title>
</head>
<body>
{% block content %}
    {% if album %}
        <div class="mainc container">
            <div class="card col-xs-12 col-sm-3 col-md-2">
                <img class="card-img-top" src="{{ album.logo }}" alt="Card image cap" height="180px" width="180px">
                <div class="card-body">
                    <h4 class="card-title album_title">{{ album.album_title }}</h4>
                    <h5 class="artist">{{ album.artist }}</h5>
                    <h5 class="genre_head">Genre : <span class="genre_detail">{{ album.genre }}</span></h5>
              </div>
            </div>
            <div id="songs_list" class="col-xs-12 col-sm-7 col-md-offset-1 col-md-8">
                <table>
                    <tr>
                        <th class="col-md-3">Song &nbsp;</th>
                        <th class="col-md-3">Duration</th>
                    </tr>
                {% for i in album.song_set.all %}
                    <tr>
                        <td class="col-md-3">{{ i.song_title }}</td>

                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    {% else %}
        <h4>Songs not added yet</h4>
    {% endif %}
{% endblock %}
</body>

music/templates/home.html
{% extends 'base.html' %}
    {% block title %}Home{% endblock %}


{% block content %}
    <div class="home container">
    {% if details %}
        {% for i in details %}
            <div class="card col-xs-6 col-sm-3 col-md-2">
              <a href="{% url 'detail' i.id %}">
                  <img class="card-img-top" src="{{ i.logo }}" alt="Card image cap">
              </a>
                <div class="card-body">
                    <h4 class="card-title"><a href="{% url 'detail' i.id %}">{{ i.album_title }}</a></h4>
                    <h5>{{ i.artist }}<div class=" playbutt"><span class="glyphicon glyphicon-play"></span> </div></h5>
              </div>
            </div>
        {% endfor %}
    {% else %}
            <h4>No album</h4>
    {% endif %}
    </div>
{% endblock %}

music/templates/songs.html
{% extends 'base.html' %}
{% block title %}Songs{% endblock %}
{% block content %}
    {% if song %}
        {% for i in song %}
            <ul style="list-style: none;">
                <li><img class="song_img" src="" height="40px" width="40px" >&emsp;{{ i.song_title }}</li>
            </ul>
        {% endfor %}
    {% else %}
        <h4>Songs not added yet</h4>
    {% endif %}
{% endblock %}